# Cloud Build configuration for all NBA services
# Uses substitution variables to support any service
#
# Usage via helper script (recommended):
#   ./bin/cloud-deploy.sh prediction-worker
#   ./bin/cloud-deploy.sh nba-phase4-precompute-processors
#
# Usage directly:
#   gcloud builds submit --config cloudbuild.yaml \
#     --substitutions=_SERVICE=prediction-worker,_DOCKERFILE=predictions/worker/Dockerfile \
#     --project nba-props-platform

steps:
  # Step 0: Download model files from GCS (for prediction-worker)
  # Creates models/ directory with monthly model files needed by the Dockerfile.
  # For non-worker services, the COPY in Dockerfile won't reference models/ so this is a no-op.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        mkdir -p models
        gcloud storage cp "gs://nba-props-platform-models/catboost/v9/monthly/*.cbm" models/ 2>/dev/null || true
        ls -la models/ 2>/dev/null || true

  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - '${_DOCKERFILE}'
      - '-t'
      - 'us-west2-docker.pkg.dev/nba-props-platform/nba-props/${_SERVICE}:latest'
      - '-t'
      - 'us-west2-docker.pkg.dev/nba-props-platform/nba-props/${_SERVICE}:${SHORT_SHA}'
      - '--build-arg'
      - 'BUILD_COMMIT=${SHORT_SHA}'
      - '--build-arg'
      - 'BUILD_TIMESTAMP=${_BUILD_TIMESTAMP}'
      - '.'

  # Step 2: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE}'
      - '--image'
      - 'us-west2-docker.pkg.dev/nba-props-platform/nba-props/${_SERVICE}:latest'
      - '--region'
      - 'us-west2'
      - '--project'
      - 'nba-props-platform'
      - '--update-env-vars'
      - 'BUILD_COMMIT=${SHORT_SHA},BUILD_TIMESTAMP=${_BUILD_TIMESTAMP}'
      - '--update-labels'
      - 'commit-sha=${SHORT_SHA}'

images:
  - 'us-west2-docker.pkg.dev/nba-props-platform/nba-props/${_SERVICE}:latest'
  - 'us-west2-docker.pkg.dev/nba-props-platform/nba-props/${_SERVICE}:${SHORT_SHA}'

substitutions:
  _SERVICE: ''
  _DOCKERFILE: ''
  _BUILD_TIMESTAMP: ''

timeout: 1200s

options:
  logging: CLOUD_LOGGING_ONLY
