# Cloud Build configuration for all NBA services
# Uses substitution variables to support any service
#
# Usage via helper script (recommended):
#   ./bin/cloud-deploy.sh prediction-worker
#   ./bin/cloud-deploy.sh nba-phase4-precompute-processors
#
# Usage directly:
#   gcloud builds submit --config cloudbuild.yaml \
#     --substitutions=_SERVICE=prediction-worker,_DOCKERFILE=predictions/worker/Dockerfile \
#     --project nba-props-platform

steps:
  # Step 0: Download production model from GCS (only for prediction-worker)
  # Reads manifest.json to find the production model dynamically.
  # Session 166: Fixed to download production model instead of monthly/*.cbm
  # Session 167: Reads from manifest.json so model promotions don't require
  # manual cloudbuild.yaml updates.
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: bash
    args:
      - '-c'
      - |
        if [ "${_SERVICE}" = "prediction-worker" ]; then
          echo "Downloading production model for prediction-worker..."
          mkdir -p models
          # Remove any existing catboost_v9 models (may be git-tracked)
          # to prevent alphabetical sort from picking the wrong model
          rm -f models/catboost_v9*.cbm
          # Read production model path from manifest.json (source of truth)
          gsutil cp "gs://nba-props-platform-models/catboost/v9/manifest.json" /tmp/manifest.json
          MODEL_GCS_PATH=$$(python3 -c "
        import json
        with open('/tmp/manifest.json') as f:
            manifest = json.load(f)
        for name, data in manifest.get('models', {}).items():
            if data.get('status') == 'production':
                print(data['gcs_path'])
                break
        ")
          if [ -z "$$MODEL_GCS_PATH" ]; then
            echo "ERROR: No production model found in manifest.json"
            exit 1
          fi
          echo "Production model from manifest: $$MODEL_GCS_PATH"
          gsutil cp "$$MODEL_GCS_PATH" models/
          ls -la models/
        else
          echo "Skipping model download (not prediction-worker)"
          mkdir -p models
        fi

  # Step 1: Build the Docker image
  # --no-cache ensures fresh source code is always picked up (Session 217/218 fix)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-f'
      - '${_DOCKERFILE}'
      - '-t'
      - 'us-west2-docker.pkg.dev/nba-props-platform/nba-props/${_SERVICE}:latest'
      - '-t'
      - 'us-west2-docker.pkg.dev/nba-props-platform/nba-props/${_SERVICE}:${SHORT_SHA}'
      - '--build-arg'
      - 'BUILD_COMMIT=${SHORT_SHA}'
      - '--build-arg'
      - 'BUILD_TIMESTAMP=${_BUILD_TIMESTAMP}'
      - '.'

  # Step 2: Push the image BEFORE deploying
  # Session 352: The `images:` section pushes AFTER all steps complete, but
  # `gcloud run deploy --image` pulls from the registry. Without this push,
  # the deploy step would pull the PREVIOUS :latest tag, deploying stale code
  # while updating BUILD_COMMIT env var — making drift checks show "up to date".
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-west2-docker.pkg.dev/nba-props-platform/nba-props/${_SERVICE}:latest'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-west2-docker.pkg.dev/nba-props-platform/nba-props/${_SERVICE}:${SHORT_SHA}'

  # Step 3: Deploy to Cloud Run
  # Session 338: Added --min-instances to prevent cold-start drift on redeploy.
  # Override per-trigger via _MIN_INSTANCES substitution (default: 0).
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE}'
      - '--image'
      - 'us-west2-docker.pkg.dev/nba-props-platform/nba-props/${_SERVICE}:latest'
      - '--region'
      - 'us-west2'
      - '--project'
      - 'nba-props-platform'
      - '--update-env-vars'
      - 'BUILD_COMMIT=${SHORT_SHA},BUILD_TIMESTAMP=${_BUILD_TIMESTAMP}'
      - '--update-labels'
      - 'commit-sha=${SHORT_SHA}'
      - '--min-instances'
      - '${_MIN_INSTANCES}'

images:
  - 'us-west2-docker.pkg.dev/nba-props-platform/nba-props/${_SERVICE}:latest'
  - 'us-west2-docker.pkg.dev/nba-props-platform/nba-props/${_SERVICE}:${SHORT_SHA}'

substitutions:
  _SERVICE: ''
  _DOCKERFILE: ''
  _BUILD_TIMESTAMP: ''
  _MIN_INSTANCES: '0'

timeout: 1200s

options:
  logging: CLOUD_LOGGING_ONLY
