# Cloud Build configuration for prediction-coordinator
# Builds from repository root with date validation fix
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'docker/predictions-coordinator.Dockerfile'
      - '-t'
      - 'gcr.io/nba-props-platform/prediction-coordinator:latest'
      - '.'

images:
  - 'gcr.io/nba-props-platform/prediction-coordinator:latest'

timeout: 900s
