-- File: schemas/bigquery/nba_orchestration/workflow_decisions.sql
-- ============================================================================
-- NBA Props Platform - Phase 1 Orchestration: Workflow Decisions
-- ============================================================================
-- Purpose: Logs every workflow evaluation decision made by master controller
-- Update: Every controller evaluation (typically hourly)
-- Entities: All workflows (morning_operations, injury_discovery, betting_lines, etc.)
-- Retention: 90 days (partition expiration)
--
-- Version: 1.0
-- Date: November 10, 2025
-- Status: Production-Ready
--
-- Decision Types:
--   - RUN: Execute workflow now (all conditions met)
--   - SKIP: Not needed now (already complete, no games, etc.)
--   - ABORT: Error in evaluation (system issue)
--
-- Use Cases:
--   - Expected vs actual execution comparison
--   - Workflow pattern analysis and optimization
--   - Alert on skipped critical workflows
--   - Trend analysis for scheduling improvements
--
-- Dependencies: None (foundational logging table)
-- ============================================================================

CREATE TABLE IF NOT EXISTS `nba-props-platform.nba_orchestration.workflow_decisions` (
  -- ==========================================================================
  -- IDENTIFIERS (2 fields)
  -- ==========================================================================
  
  decision_id STRING NOT NULL,
    -- Unique decision identifier (UUID)
    -- Format: Full UUID generated by controller
    -- Example: "550e8400-e29b-41d4-a716-446655440000"
    -- Used for: Correlation, debugging specific evaluations
  
  decision_time TIMESTAMP NOT NULL,
    -- When decision was made in UTC
    -- Partition key (daily partitions)
    -- Used for: Time-based queries, expected vs actual comparison
    -- Always filter on this field for efficient queries
  
  -- ==========================================================================
  -- WORKFLOW CONTEXT (1 field)
  -- ==========================================================================
  
  workflow_name STRING NOT NULL,
    -- Workflow being evaluated
    -- Examples:
    --   'betting_lines' (pre-game odds collection)
    --   'injury_discovery' (find when injury report published)
    --   'morning_operations' (daily foundation data)
    --   'post_game_window_1' (first post-game collection)
    -- Naming convention: [purpose]_[type]
    -- Used for: Grouping by workflow, pattern analysis
  
  -- ==========================================================================
  -- DECISION RESULT (2 fields)
  -- ==========================================================================
  
  action STRING NOT NULL,
    -- Decision result
    -- Values:
    --   'RUN' = Execute workflow now (conditions met)
    --   'SKIP' = Not needed now (already done, no games, etc.)
    --   'ABORT' = Error in evaluation (system issue)
    -- Used for: Workflow success tracking, expected vs actual
  
  reason STRING NOT NULL,
    -- Human-readable explanation for decision
    -- Examples:
    --   'Ready: 5 games today, 3.2h until first game'
    --   'Already completed successfully today'
    --   'No games scheduled today'
    --   'Discovery attempt 3/12: No data found yet'
    --   'Error: Unable to query schedule'
    -- Used for: Debugging, understanding workflow behavior
  
  -- ==========================================================================
  -- DECISION CONTEXT (1 field - JSON)
  -- ==========================================================================
  
  context JSON,
    -- Additional decision context
    -- Structure varies by workflow type:
    -- {
    --   "games_today": int,           // Number of games scheduled
    --   "hours_until_game": float,    // Time until first game
    --   "attempts_today": int,        // Discovery mode attempts
    --   "last_run": timestamp,        // Last successful execution
    --   "record_count": int,          // Records from last run
    --   "next_game_time": timestamp,  // Next game start
    --   "evaluation_details": {...}   // Workflow-specific data
    -- }
    -- Example: {"games_today": 5, "hours_until_game": 3.2, "attempts_today": 2}
    -- Used for: Detailed analysis, debugging edge cases
  
  -- ==========================================================================
  -- EXECUTION PLAN (2 fields)
  -- ==========================================================================
  
  scrapers_triggered ARRAY<STRING>,
    -- List of scraper names to execute if action='RUN'
    -- Examples:
    --   ['nbac_injury_report'] (single scraper)
    --   ['oddsa_events', 'oddsa_player_props'] (multiple scrapers)
    -- Empty array if: action='SKIP' or action='ABORT'
    -- Used for: Understanding workflow composition
  
  target_games ARRAY<STRING>,
    -- Specific game IDs to process
    -- Format: YYYYMMDD{AWAY}_{HOME}
    -- Example: ['20250115LAL_GSW', '20250115BOS_MIA']
    -- Used for: Post-game collection workflows
    -- Empty array for: Global workflows (non-game-specific)
  
  -- ==========================================================================
  -- SCHEDULING (1 field)
  -- ==========================================================================
  
  next_check_time TIMESTAMP,
    -- When to evaluate this workflow again
    -- Used for: Scheduling optimization, reducing unnecessary evaluations
    -- NULL if: Workflow disabled, one-time execution
    -- Example: Next hour for discovery mode, next day for daily workflows
  
  -- ==========================================================================
  -- PRIORITY & ALERTING (2 fields)
  -- ==========================================================================
  
  priority STRING,
    -- Workflow priority level
    -- Values:
    --   'CRITICAL' = Must run (foundation data, betting lines)
    --   'HIGH' = Important (injury reports, odds updates)
    --   'MEDIUM' = Normal operations (backfills, analytics)
    --   'LOW' = Nice to have (reference data updates)
    --   'MANUAL' = Manual-only execution
    -- Used for: Alert routing, scheduling conflicts
  
  alert_level STRING,
    -- Alert severity for this decision
    -- Values:
    --   'NONE' = Normal operation
    --   'INFO' = Informational (skipped non-critical workflow)
    --   'WARNING' = Attention needed (multiple skips, late execution)
    --   'CRITICAL' = Immediate action required (critical workflow failed)
    -- Used for: Alert routing, incident detection
  
  -- ==========================================================================
  -- SYSTEM METADATA (3 fields)
  -- ==========================================================================
  
  controller_version STRING,
    -- Master controller code version
    -- Format: "v1.2.3" or git commit hash
    -- Example: "v1.0.0", "abc123def"
    -- Used for: Tracking behavior changes over time
    -- NULL for: Initial implementation
  
  environment STRING,
    -- Execution environment
    -- Values: 'prod', 'dev', 'local'
    -- Used for: Separating test from production decisions
  
  triggered_by STRING,
    -- What triggered this evaluation
    -- Examples:
    --   'cloud-scheduler' (hourly evaluation)
    --   'manual-api-call' (testing)
    --   'local-test' (development)
    -- Used for: Understanding evaluation patterns
  
  -- ==========================================================================
  -- METADATA (1 field)
  -- ==========================================================================
  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
    -- Row creation timestamp (auto-populated by BigQuery)
    -- Used for: Audit trail, data freshness checks

)
PARTITION BY DATE(decision_time)
CLUSTER BY workflow_name, action, alert_level
OPTIONS(
  description = "Logs every workflow evaluation decision for trend analysis and monitoring. Supports expected vs actual comparison for detecting missed executions. Partition key: decision_time (daily). Cluster by: workflow_name, action, alert_level. CRITICAL TABLE for Phase 1 orchestration monitoring.",
  partition_expiration_days = 90
);

-- ============================================================================
-- FIELD SUMMARY
-- ============================================================================
-- Total fields: 14
--   - Identifiers: 2 (decision_id, decision_time)
--   - Workflow context: 1 (workflow_name)
--   - Decision result: 2 (action, reason)
--   - Context: 1 (context JSON)
--   - Execution plan: 2 (scrapers_triggered, target_games)
--   - Scheduling: 1 (next_check_time)
--   - Priority & alerting: 2 (priority, alert_level)
--   - System metadata: 3 (controller_version, environment, triggered_by)
--   - Metadata: 1 (created_at)
-- ============================================================================

-- ============================================================================
-- SAMPLE ROW (RUN Decision - Betting Lines)
-- ============================================================================
/*
{
  "decision_id": "550e8400-e29b-41d4-a716-446655440000",
  "decision_time": "2025-01-15T16:00:00Z",
  "workflow_name": "betting_lines",
  "action": "RUN",
  "reason": "Ready: 8 games today, 3.5h until first game",
  "context": {
    "games_today": 8,
    "hours_until_game": 3.5,
    "first_game_time": "2025-01-15T19:30:00Z",
    "last_successful_run": "2025-01-14T16:00:00Z",
    "evaluation_time_ms": 245
  },
  "scrapers_triggered": ["oddsa_events", "oddsa_player_props"],
  "target_games": [],
  "next_check_time": "2025-01-15T17:00:00Z",
  "priority": "CRITICAL",
  "alert_level": "NONE",
  "controller_version": "v1.0.0",
  "environment": "prod",
  "triggered_by": "cloud-scheduler",
  "insert_time": "2025-01-15T16:00:01Z"
}
*/

-- ============================================================================
-- SAMPLE ROW (SKIP Decision - Already Complete)
-- ============================================================================
/*
{
  "decision_id": "660e8400-e29b-41d4-a716-446655440001",
  "decision_time": "2025-01-15T07:00:00Z",
  "workflow_name": "morning_operations",
  "action": "SKIP",
  "reason": "Already completed successfully today at 06:05",
  "context": {
    "games_today": 8,
    "last_successful_run": "2025-01-15T06:05:00Z",
    "record_count": 82,
    "run_once_daily": true,
    "evaluation_time_ms": 120
  },
  "scrapers_triggered": [],
  "target_games": [],
  "next_check_time": "2025-01-16T06:00:00Z",
  "priority": "HIGH",
  "alert_level": "NONE",
  "controller_version": "v1.0.0",
  "environment": "prod",
  "triggered_by": "cloud-scheduler",
  "insert_time": "2025-01-15T07:00:01Z"
}
*/

-- ============================================================================
-- SAMPLE ROW (RUN Decision - Discovery Mode)
-- ============================================================================
/*
{
  "decision_id": "770e8400-e29b-41d4-a716-446655440002",
  "decision_time": "2025-01-15T12:00:00Z",
  "workflow_name": "injury_discovery",
  "action": "RUN",
  "reason": "Discovery attempt 4/12: No data found yet",
  "context": {
    "games_today": 8,
    "attempts_today": 3,
    "max_attempts": 12,
    "last_attempt_status": "no_data",
    "last_attempt_time": "2025-01-15T11:00:00Z",
    "retry_interval_hours": 1,
    "evaluation_time_ms": 180
  },
  "scrapers_triggered": ["nbac_injury_report"],
  "target_games": [],
  "next_check_time": "2025-01-15T13:00:00Z",
  "priority": "MEDIUM",
  "alert_level": "NONE",
  "controller_version": "v1.0.0",
  "environment": "prod",
  "triggered_by": "cloud-scheduler",
  "insert_time": "2025-01-15T12:00:01Z"
}
*/

-- ============================================================================
-- SAMPLE ROW (SKIP Decision - Discovery Success)
-- ============================================================================
/*
{
  "decision_id": "880e8400-e29b-41d4-a716-446655440003",
  "decision_time": "2025-01-15T13:00:00Z",
  "workflow_name": "injury_discovery",
  "action": "SKIP",
  "reason": "Already found data today: 12 records at 12:30",
  "context": {
    "games_today": 8,
    "attempts_today": 5,
    "last_successful_run": "2025-01-15T12:30:00Z",
    "record_count": 12,
    "discovery_complete": true,
    "evaluation_time_ms": 95
  },
  "scrapers_triggered": [],
  "target_games": [],
  "next_check_time": "2025-01-16T11:00:00Z",
  "priority": "MEDIUM",
  "alert_level": "NONE",
  "controller_version": "v1.0.0",
  "environment": "prod",
  "triggered_by": "cloud-scheduler",
  "insert_time": "2025-01-15T13:00:01Z"
}
*/

-- ============================================================================
-- SAMPLE ROW (ABORT Decision - Evaluation Error)
-- ============================================================================
/*
{
  "decision_id": "990e8400-e29b-41d4-a716-446655440004",
  "decision_time": "2025-01-15T10:00:00Z",
  "workflow_name": "post_game_window_1",
  "action": "ABORT",
  "reason": "Error: Unable to query schedule table",
  "context": {
    "error_type": "BigQueryException",
    "error_message": "Table not found: nba_raw.nbac_schedule",
    "evaluation_time_ms": 5230
  },
  "scrapers_triggered": [],
  "target_games": [],
  "next_check_time": "2025-01-15T11:00:00Z",
  "priority": "HIGH",
  "alert_level": "CRITICAL",
  "controller_version": "v1.0.0",
  "environment": "prod",
  "triggered_by": "cloud-scheduler",
  "insert_time": "2025-01-15T10:00:05Z"
}
*/

-- ============================================================================
-- VALIDATION QUERIES
-- ============================================================================

-- Query 1: Today's workflow decisions summary
-- Purpose: Quick overview of all workflow activity today
-- Expected: All workflows evaluated, most SKIP (already complete)
-- SELECT 
--   workflow_name,
--   action,
--   COUNT(*) as decisions,
--   MAX(decision_time) as last_decision,
--   STRING_AGG(DISTINCT reason ORDER BY reason LIMIT 3) as sample_reasons
-- FROM `nba-props-platform.nba_orchestration.workflow_decisions`
-- WHERE DATE(decision_time) = CURRENT_DATE()
-- GROUP BY workflow_name, action
-- ORDER BY workflow_name, action;

-- -- Query 2: Expected vs actual (detect missing executions)
-- -- Purpose: Compare expected schedule to actual workflow runs
-- -- Expected: All expected workflows executed on time
-- WITH expected AS (
--   SELECT 
--     workflow_name,
--     expected_run_time,
--     reason as expected_reason
--   FROM `nba-props-platform.nba_orchestration.daily_expected_schedule`
--   WHERE date = CURRENT_DATE('America/New_York')
-- ),
-- actual AS (
--   SELECT 
--     workflow_name,
--     decision_time as actual_run_time,
--     action,
--     reason as actual_reason
--   FROM `nba-props-platform.nba_orchestration.workflow_decisions`
--   WHERE DATE(decision_time, 'America/New_York') = CURRENT_DATE('America/New_York')
--     AND action = 'RUN'
-- )
-- SELECT 
--   expected.workflow_name,
--   FORMAT_TIMESTAMP('%H:%M', expected.expected_run_time, 'America/New_York') as expected_time,
--   FORMAT_TIMESTAMP('%H:%M', actual.actual_run_time, 'America/New_York') as actual_time,
--   CASE 
--     WHEN actual.workflow_name IS NULL THEN '🔴 MISSING'
--     WHEN TIMESTAMP_DIFF(actual.actual_run_time, expected.expected_run_time, MINUTE) > 30 THEN '🟡 LATE'
--     ELSE '✅ ON TIME'
--   END as status,
--   expected.expected_reason,
--   actual.actual_reason
-- FROM expected
-- LEFT JOIN actual 
--   ON expected.workflow_name = actual.workflow_name
--   AND TIMESTAMP_DIFF(actual.actual_run_time, expected.expected_run_time, MINUTE) < 60
-- ORDER BY expected.expected_run_time;

-- -- Query 3: Alert on critical workflow failures
-- -- Purpose: Detect critical workflows that were skipped or aborted
-- -- Expected: Empty result (no critical issues)
-- SELECT 
--   workflow_name,
--   decision_time,
--   action,
--   reason,
--   priority,
--   alert_level
-- FROM `nba-props-platform.nba_orchestration.workflow_decisions`
-- WHERE DATE(decision_time) = CURRENT_DATE()
--   AND priority = 'CRITICAL'
--   AND action IN ('SKIP', 'ABORT')
--   AND alert_level IN ('WARNING', 'CRITICAL')
-- ORDER BY decision_time DESC;

-- -- Query 4: Discovery mode progress tracking
-- -- Purpose: Monitor discovery workflows until they find data
-- -- Expected: Attempts increase until success, then stop
-- SELECT 
--   workflow_name,
--   action,
--   reason,
--   JSON_VALUE(context, '$.attempts_today') as attempts,
--   JSON_VALUE(context, '$.max_attempts') as max_attempts,
--   decision_time
-- FROM `nba-props-platform.nba_orchestration.workflow_decisions`
-- WHERE DATE(decision_time) = CURRENT_DATE()
--   AND workflow_name LIKE '%discovery%'
-- ORDER BY workflow_name, decision_time;

-- -- Query 5: Workflow execution patterns (last 7 days)
-- -- Purpose: Understand typical workflow behavior
-- -- Expected: Consistent daily patterns, no unexpected gaps
-- SELECT 
--   workflow_name,
--   DATE(decision_time) as date,
--   COUNT(*) as evaluations,
--   COUNTIF(action = 'RUN') as runs,
--   COUNTIF(action = 'SKIP') as skips,
--   COUNTIF(action = 'ABORT') as aborts,
--   MIN(decision_time) as first_eval,
--   MAX(decision_time) as last_eval
-- FROM `nba-props-platform.nba_orchestration.workflow_decisions`
-- WHERE DATE(decision_time) >= DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY)
-- GROUP BY workflow_name, DATE(decision_time)
-- ORDER BY workflow_name, date DESC;

-- -- Query 6: Evaluation performance
-- -- Purpose: Detect slow evaluations that might cause delays
-- -- Expected: Most evaluations <1 second
-- SELECT 
--   workflow_name,
--   ROUND(AVG(CAST(JSON_VALUE(context, '$.evaluation_time_ms') AS FLOAT64)), 0) as avg_eval_ms,
--   ROUND(MAX(CAST(JSON_VALUE(context, '$.evaluation_time_ms') AS FLOAT64)), 0) as max_eval_ms,
--   COUNT(*) as evaluations
-- FROM `nba-props-platform.nba_orchestration.workflow_decisions`
-- WHERE DATE(decision_time) >= DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY)
--   AND JSON_VALUE(context, '$.evaluation_time_ms') IS NOT NULL
-- GROUP BY workflow_name
-- ORDER BY avg_eval_ms DESC;

-- -- ============================================================================
-- -- MONITORING QUERIES
-- -- ============================================================================

-- -- Alert: Critical workflow not run in expected timeframe
-- -- Threshold: CRITICAL workflow should run within expected window
-- SELECT 
--   'workflow_decisions' as alert_source,
--   workflow_name,
--   MAX(decision_time) as last_evaluation,
--   TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), MAX(decision_time), HOUR) as hours_since_last_eval
-- FROM `nba-props-platform.nba_orchestration.workflow_decisions`
-- WHERE priority = 'CRITICAL'
--   AND DATE(decision_time) = CURRENT_DATE()
-- GROUP BY workflow_name
-- HAVING TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), MAX(decision_time), HOUR) > 2;

-- -- Alert: Too many ABORT actions
-- -- Threshold: >3 aborts in a day indicates systemic issues
-- SELECT 
--   'workflow_decisions' as alert_source,
--   workflow_name,
--   COUNT(*) as abort_count,
--   STRING_AGG(DISTINCT reason ORDER BY reason) as abort_reasons
-- FROM `nba-props-platform.nba_orchestration.workflow_decisions`
-- WHERE DATE(decision_time) = CURRENT_DATE()
--   AND action = 'ABORT'
-- GROUP BY workflow_name
-- HAVING COUNT(*) > 3;

-- -- Alert: Workflow not evaluated today
-- -- Threshold: Every workflow should be evaluated at least once per day
-- SELECT 
--   'workflow_decisions' as alert_source,
--   expected.workflow_name,
--   'Not evaluated today' as issue
-- FROM `nba-props-platform.nba_orchestration.daily_expected_schedule` expected
-- LEFT JOIN `nba-props-platform.nba_orchestration.workflow_decisions` actual
--   ON expected.workflow_name = actual.workflow_name
--   AND DATE(actual.decision_time) = CURRENT_DATE()
-- WHERE expected.date = CURRENT_DATE()
--   AND actual.workflow_name IS NULL;

-- -- ============================================================================
-- -- HELPER VIEWS
-- -- ============================================================================

-- -- View: Today's workflow summary
-- CREATE OR REPLACE VIEW `nba-props-platform.nba_orchestration.v_todays_workflows` AS
-- SELECT 
--   workflow_name,
--   priority,
--   COUNT(*) as total_evaluations,
--   COUNTIF(action = 'RUN') as times_run,
--   COUNTIF(action = 'SKIP') as times_skipped,
--   COUNTIF(action = 'ABORT') as times_aborted,
--   MIN(decision_time) as first_evaluation,
--   MAX(decision_time) as last_evaluation,
--   MAX(CASE WHEN action = 'RUN' THEN decision_time END) as last_run_time
-- FROM `nba-props-platform.nba_orchestration.workflow_decisions`
-- WHERE DATE(decision_time) = CURRENT_DATE()
-- GROUP BY workflow_name, priority
-- ORDER BY priority, workflow_name;

-- -- View: Recent workflow failures
-- CREATE OR REPLACE VIEW `nba-props-platform.nba_orchestration.v_recent_workflow_failures` AS
-- SELECT 
--   workflow_name,
--   decision_time,
--   action,
--   reason,
--   priority,
--   alert_level,
--   controller_version
-- FROM `nba-props-platform.nba_orchestration.workflow_decisions`
-- WHERE DATE(decision_time) >= DATE_SUB(CURRENT_DATE(), INTERVAL 3 DAY)
--   AND (action = 'ABORT' OR alert_level IN ('WARNING', 'CRITICAL'))
-- ORDER BY decision_time DESC;

-- ============================================================================
-- DEPLOYMENT CHECKLIST
-- ============================================================================
-- [ ] Create table in nba_orchestration dataset
-- [ ] Verify partitioning (daily on decision_time)
-- [ ] Verify clustering (workflow_name, action, alert_level)
-- [ ] Test with sample insert
-- [ ] Validate JSON context field
-- [ ] Test expected vs actual query
-- [ ] Enable monitoring queries
-- [ ] Configure alerts in Grafana
-- [ ] Document alert thresholds
-- [ ] Create helper views
-- ============================================================================
