
TEAM_INFO = {
    "1":  {"abbreviation": "ATL", "displayName": "Atlanta Hawks"},
    "2":  {"abbreviation": "BOS", "displayName": "Boston Celtics"},
    "3":  {"abbreviation": "NOP", "displayName": "New Orleans Pelicans"},
    "4":  {"abbreviation": "CHI", "displayName": "Chicago Bulls"},
    "5":  {"abbreviation": "CLE", "displayName": "Cleveland Cavaliers"},
    "6":  {"abbreviation": "DAL", "displayName": "Dallas Mavericks"},
    "7":  {"abbreviation": "DEN", "displayName": "Denver Nuggets"},
    "8":  {"abbreviation": "DET", "displayName": "Detroit Pistons"},
    "9":  {"abbreviation": "GSW", "displayName": "Golden State Warriors"},
    "10": {"abbreviation": "HOU", "displayName": "Houston Rockets"},
    "11": {"abbreviation": "IND", "displayName": "Indiana Pacers"},
    "12": {"abbreviation": "LAC", "displayName": "LA Clippers"},
    "13": {"abbreviation": "LAL", "displayName": "Los Angeles Lakers"},
    "14": {"abbreviation": "MIA", "displayName": "Miami Heat"},
    "15": {"abbreviation": "MIL", "displayName": "Milwaukee Bucks"},
    "16": {"abbreviation": "MIN", "displayName": "Minnesota Timberwolves"},
    "17": {"abbreviation": "BKN", "displayName": "Brooklyn Nets"},
    "18": {"abbreviation": "NYK", "displayName": "New York Knicks"},
    "19": {"abbreviation": "ORL", "displayName": "Orlando Magic"},
    "20": {"abbreviation": "PHI", "displayName": "Philadelphia 76ers"},
    "21": {"abbreviation": "PHX", "displayName": "Phoenix Suns"},
    "22": {"abbreviation": "POR", "displayName": "Portland Trail Blazers"},
    "23": {"abbreviation": "SAC", "displayName": "Sacramento Kings"},
    "24": {"abbreviation": "WAS", "displayName": "Washington Wizards"},
    "25": {"abbreviation": "OKC", "displayName": "Oklahoma City Thunder"},
    "26": {"abbreviation": "UTA", "displayName": "Utah Jazz"},
    "27": {"abbreviation": "SAS", "displayName": "San Antonio Spurs"},
    "28": {"abbreviation": "TOR", "displayName": "Toronto Raptors"},
    "29": {"abbreviation": "MEM", "displayName": "Memphis Grizzlies"},
    "30": {"abbreviation": "CHA", "displayName": "Charlotte Hornets"},
}

