# Cloud Run Job Configuration for MLB Prediction Coverage Validator
# Validates prediction completeness and quality

apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: mlb-prediction-coverage-validator
  labels:
    cloud.googleapis.com/location: us-west2
    sport: mlb
    type: validation
    component: prediction-coverage
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      taskCount: 1
      template:
        spec:
          maxRetries: 1
          timeoutSeconds: 600  # 10 minutes
          serviceAccountName: mlb-monitoring-sa@nba-props-platform.iam.gserviceaccount.com
          containers:
          - image: us-west2-docker.pkg.dev/nba-props-platform/mlb-validators/prediction-coverage-validator:latest
            env:
            - name: GCP_PROJECT_ID
              value: "nba-props-platform"
            - name: PYTHONPATH
              value: "."
            - name: ENVIRONMENT
              value: "production"
            resources:
              limits:
                cpu: "1000m"
                memory: "256Mi"  # Optimized from 512Mi - validators are lightweight
            args:
            - "--start-date"
            - "today"
            - "--end-date"
            - "today"
