#!/bin/bash
# FILE: processor_backfill/bdl_boxscores/deploy.sh

# Deploy Ball Don't Lie Boxscores Processor Backfill Job

set -e

echo "Deploying Ball Don't Lie Boxscores Processor Backfill Job..."

# Use standardized processor backfill deployment script
./bin/processors/deploy/deploy_processor_backfill_job.sh bdl_boxscores

echo "Deployment complete!"
echo ""
echo "CRITICAL: This deployment includes game ID format fix (HOME_AWAY → AWAY_HOME)"
echo "Existing database data should be deleted and reprocessed for format consistency."
echo ""
echo "Test Commands:"
echo "  # Dry run (single recovery date):"
echo "  gcloud run jobs execute bdl-boxscores-processor-backfill --args=--start-date=2022-01-10,--end-date=2022-01-10,--dry-run --region=us-west2"
echo ""
echo "  # Test single recovery date (format validation):"
echo "  gcloud run jobs execute bdl-boxscores-processor-backfill --args=--start-date=2022-01-10,--end-date=2022-01-10 --region=us-west2"
echo ""
echo "  # Recovery batch 1 (2022 processor failures):"
echo "  gcloud run jobs execute bdl-boxscores-processor-backfill --args=--start-date=2022-01-10,--end-date=2022-03-31 --region=us-west2"
echo ""
echo "  # Recovery batch 2 (2023 processor failures):"
echo "  gcloud run jobs execute bdl-boxscores-processor-backfill --args=--start-date=2023-03-05,--end-date=2023-03-07 --region=us-west2"
echo ""
echo "  # Full historical backfill (all seasons with format fix):"
echo "  gcloud run jobs execute bdl-boxscores-processor-backfill --args=--start-date=2021-10-01,--end-date=2025-06-30 --region=us-west2"
echo ""
echo "  # Current season only:"
echo "  gcloud run jobs execute bdl-boxscores-processor-backfill --args=--start-date=2024-10-01,--end-date=2025-06-30 --region=us-west2"
echo ""
echo "Monitor logs:"
echo "  ./bin/processor_backfill/bdl_boxscores_backfill_monitor.sh"
echo ""
echo "Or monitor specific execution:"
echo "  gcloud run jobs executions logs [execution-id] --region=us-west2 --follow"
echo ""
echo "Database Cleanup (RECOMMENDED before full reprocessing):"
echo "  # Backup existing data:"
echo "  bq query --use_legacy_sql=false \"CREATE TABLE \\\`nba-props-platform.nba_raw.bdl_player_boxscores_backup\\\` AS SELECT * FROM \\\`nba-props-platform.nba_raw.bdl_player_boxscores\\\`\""
echo ""
echo "  # Delete all existing data (for format consistency):"
echo "  bq query --use_legacy_sql=false \"DELETE FROM \\\`nba-props-platform.nba_raw.bdl_player_boxscores\\\` WHERE TRUE\""
echo ""
echo "Validate Results:"
echo "  # Check game ID format compliance (should be 100% AWAY_HOME format):"
echo "  bq query --use_legacy_sql=false \"SELECT game_date, game_id, home_team_abbr, away_team_abbr, CASE WHEN SPLIT(game_id, '_')[OFFSET(1)] = away_team_abbr AND SPLIT(game_id, '_')[OFFSET(2)] = home_team_abbr THEN 'CORRECT_AWAY_HOME' WHEN SPLIT(game_id, '_')[OFFSET(1)] = home_team_abbr AND SPLIT(game_id, '_')[OFFSET(2)] = away_team_abbr THEN 'WRONG_HOME_AWAY' ELSE 'UNKNOWN_FORMAT' END as format_check FROM \\\`nba-props-platform.nba_raw.bdl_player_boxscores\\\` WHERE game_date >= '2022-01-10' GROUP BY game_date, game_id, home_team_abbr, away_team_abbr ORDER BY game_date LIMIT 10\""
echo ""
echo "  # Check recovery progress (target dates):"
echo "  bq query --use_legacy_sql=false \"SELECT game_date, COUNT(DISTINCT game_id) as games, COUNT(*) as player_records FROM \\\`nba-props-platform.nba_raw.bdl_player_boxscores\\\` WHERE game_date IN ('2022-01-10', '2022-01-26', '2022-02-03', '2023-03-05', '2023-03-06', '2023-03-07') GROUP BY game_date ORDER BY game_date\""
echo ""
echo "  # Check data quality:"
echo "  bq query --use_legacy_sql=false \"SELECT game_date, AVG(points) as avg_points, COUNT(DISTINCT player_full_name) as unique_players, COUNT(*) as total_records FROM \\\`nba-props-platform.nba_raw.bdl_player_boxscores\\\` WHERE game_date >= CURRENT_DATE() - 7 GROUP BY game_date ORDER BY game_date DESC\""
echo ""
echo "  # Validate team abbreviations:"
echo "  bq query --use_legacy_sql=false \"SELECT team_abbr, COUNT(*) as count FROM \\\`nba-props-platform.nba_raw.bdl_player_boxscores\\\` WHERE game_date >= '2022-01-10' GROUP BY team_abbr ORDER BY count DESC\""
echo ""
echo "Recovery Status Check:"
echo "  # Run validation script to check coverage improvement:"
echo "  python bin/processors/validation/validate_nba_boxscore_coverage.py"
echo ""
echo "NEXT STEPS:"
echo "1. Test with single date first: 2022-01-10"
echo "2. Validate game ID format is correct (AWAY_HOME)"
echo "3. If successful, run full cleanup and reprocessing"
echo "4. Monitor analytics recovery after format fix"
